#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <list>
#include <sstream>
#include <ctime>
#include <chrono>
#include "menu.h"
#include "movie.h"
#include "main.h"
#include "hall.h"
#include "show.h"
#include "colors.h"
#include "movie_repo.h"
#include "repository.h"
#include "screen_utility.h"